name: repoman

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run repoman
        uses: gentoo-monero/repoman-action@v1
